# Check on http://lint.travis-ci.org/ after modifying!
language: python
python:
  - "2.7"
install:
  - pip install numpy==1.5.1 Cython==0.17
  - pip install cogent==1.5.3
  - pip install ftp://thebeast.colorado.edu/pub/biom-format-releases/biom-format-1.1.2.tar.gz
  - pip install .
script:
  - python tests/all_tests.py
