# Check on http://lint.travis-ci.org/ after modifying!
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install r-base
  - Rscript -e 'install.packages("ape", dep=TRUE, repos="http://cran.r-project.org")'
install:
  - pip install numpy==1.5.1 Cython==0.17
  - pip install cogent==1.5.3
  - pip install https://github.com/biocore/biom-format/archive/1.1.2.tar.gz
  - pip install .
script:
  - python tests/all_tests.py
